# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20170408_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='messeges',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='messeges',
            name='messege',
            field=models.TextField(blank=True, default=''),
        ),
    ]
