# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0003_auto_20170409_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('curr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserSeenList', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='Unneccessary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
